# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from extendedkalmanfilters/FusedMesurements.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FusedMesurements(genpy.Message):
  _md5sum = "78dd8106ff3952f3bd4013441cdc9454"
  _type = "extendedkalmanfilters/FusedMesurements"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x_estimated_
float32 y_estimated_
uint64 time_stamp_
float32 vx_estimated_
float32 vy_estimated_
float32 x_gt_
float32 y_gt_
float32 vx_gt_
float32 vy_gt_
"""
  __slots__ = ['x_estimated_','y_estimated_','time_stamp_','vx_estimated_','vy_estimated_','x_gt_','y_gt_','vx_gt_','vy_gt_']
  _slot_types = ['float32','float32','uint64','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_estimated_,y_estimated_,time_stamp_,vx_estimated_,vy_estimated_,x_gt_,y_gt_,vx_gt_,vy_gt_

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FusedMesurements, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_estimated_ is None:
        self.x_estimated_ = 0.
      if self.y_estimated_ is None:
        self.y_estimated_ = 0.
      if self.time_stamp_ is None:
        self.time_stamp_ = 0
      if self.vx_estimated_ is None:
        self.vx_estimated_ = 0.
      if self.vy_estimated_ is None:
        self.vy_estimated_ = 0.
      if self.x_gt_ is None:
        self.x_gt_ = 0.
      if self.y_gt_ is None:
        self.y_gt_ = 0.
      if self.vx_gt_ is None:
        self.vx_gt_ = 0.
      if self.vy_gt_ is None:
        self.vy_gt_ = 0.
    else:
      self.x_estimated_ = 0.
      self.y_estimated_ = 0.
      self.time_stamp_ = 0
      self.vx_estimated_ = 0.
      self.vy_estimated_ = 0.
      self.x_gt_ = 0.
      self.y_gt_ = 0.
      self.vx_gt_ = 0.
      self.vy_gt_ = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2fQ6f().pack(_x.x_estimated_, _x.y_estimated_, _x.time_stamp_, _x.vx_estimated_, _x.vy_estimated_, _x.x_gt_, _x.y_gt_, _x.vx_gt_, _x.vy_gt_))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.x_estimated_, _x.y_estimated_, _x.time_stamp_, _x.vx_estimated_, _x.vy_estimated_, _x.x_gt_, _x.y_gt_, _x.vx_gt_, _x.vy_gt_,) = _get_struct_2fQ6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2fQ6f().pack(_x.x_estimated_, _x.y_estimated_, _x.time_stamp_, _x.vx_estimated_, _x.vy_estimated_, _x.x_gt_, _x.y_gt_, _x.vx_gt_, _x.vy_gt_))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.x_estimated_, _x.y_estimated_, _x.time_stamp_, _x.vx_estimated_, _x.vy_estimated_, _x.x_gt_, _x.y_gt_, _x.vx_gt_, _x.vy_gt_,) = _get_struct_2fQ6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fQ6f = None
def _get_struct_2fQ6f():
    global _struct_2fQ6f
    if _struct_2fQ6f is None:
        _struct_2fQ6f = struct.Struct("<2fQ6f")
    return _struct_2fQ6f
