// Generated by gencpp from file extendedkalmanfilters/RadarMeasurements.msg
// DO NOT EDIT!


#ifndef EXTENDEDKALMANFILTERS_MESSAGE_RADARMEASUREMENTS_H
#define EXTENDEDKALMANFILTERS_MESSAGE_RADARMEASUREMENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace extendedkalmanfilters
{
template <class ContainerAllocator>
struct RadarMeasurements_
{
  typedef RadarMeasurements_<ContainerAllocator> Type;

  RadarMeasurements_()
    : sensor_type_()
    , rho_measured_(0.0)
    , phi_measured_(0.0)
    , rhodot_measured_(0.0)
    , time_stamp_(0)
    , x_ground_truth_(0.0)
    , y_ground_truth_(0.0)
    , vx_ground_truth_(0.0)
    , vy_ground_truth_(0.0)  {
    }
  RadarMeasurements_(const ContainerAllocator& _alloc)
    : sensor_type_(_alloc)
    , rho_measured_(0.0)
    , phi_measured_(0.0)
    , rhodot_measured_(0.0)
    , time_stamp_(0)
    , x_ground_truth_(0.0)
    , y_ground_truth_(0.0)
    , vx_ground_truth_(0.0)
    , vy_ground_truth_(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_type__type;
  _sensor_type__type sensor_type_;

   typedef float _rho_measured__type;
  _rho_measured__type rho_measured_;

   typedef float _phi_measured__type;
  _phi_measured__type phi_measured_;

   typedef float _rhodot_measured__type;
  _rhodot_measured__type rhodot_measured_;

   typedef uint64_t _time_stamp__type;
  _time_stamp__type time_stamp_;

   typedef float _x_ground_truth__type;
  _x_ground_truth__type x_ground_truth_;

   typedef float _y_ground_truth__type;
  _y_ground_truth__type y_ground_truth_;

   typedef float _vx_ground_truth__type;
  _vx_ground_truth__type vx_ground_truth_;

   typedef float _vy_ground_truth__type;
  _vy_ground_truth__type vy_ground_truth_;





  typedef boost::shared_ptr< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> const> ConstPtr;

}; // struct RadarMeasurements_

typedef ::extendedkalmanfilters::RadarMeasurements_<std::allocator<void> > RadarMeasurements;

typedef boost::shared_ptr< ::extendedkalmanfilters::RadarMeasurements > RadarMeasurementsPtr;
typedef boost::shared_ptr< ::extendedkalmanfilters::RadarMeasurements const> RadarMeasurementsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator1> & lhs, const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator2> & rhs)
{
  return lhs.sensor_type_ == rhs.sensor_type_ &&
    lhs.rho_measured_ == rhs.rho_measured_ &&
    lhs.phi_measured_ == rhs.phi_measured_ &&
    lhs.rhodot_measured_ == rhs.rhodot_measured_ &&
    lhs.time_stamp_ == rhs.time_stamp_ &&
    lhs.x_ground_truth_ == rhs.x_ground_truth_ &&
    lhs.y_ground_truth_ == rhs.y_ground_truth_ &&
    lhs.vx_ground_truth_ == rhs.vx_ground_truth_ &&
    lhs.vy_ground_truth_ == rhs.vy_ground_truth_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator1> & lhs, const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace extendedkalmanfilters

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cfdab16d9df6f0eace3ca39d1e59ae0";
  }

  static const char* value(const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cfdab16d9df6f0eULL;
  static const uint64_t static_value2 = 0xace3ca39d1e59ae0ULL;
};

template<class ContainerAllocator>
struct DataType< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "extendedkalmanfilters/RadarMeasurements";
  }

  static const char* value(const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sensor_type_\n"
"float32 rho_measured_\n"
"float32 phi_measured_\n"
"float32 rhodot_measured_\n"
"uint64 time_stamp_\n"
"float32 x_ground_truth_\n"
"float32 y_ground_truth_\n"
"float32 vx_ground_truth_\n"
"float32 vy_ground_truth_\n"
;
  }

  static const char* value(const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_type_);
      stream.next(m.rho_measured_);
      stream.next(m.phi_measured_);
      stream.next(m.rhodot_measured_);
      stream.next(m.time_stamp_);
      stream.next(m.x_ground_truth_);
      stream.next(m.y_ground_truth_);
      stream.next(m.vx_ground_truth_);
      stream.next(m.vy_ground_truth_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarMeasurements_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::extendedkalmanfilters::RadarMeasurements_<ContainerAllocator>& v)
  {
    s << indent << "sensor_type_: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor_type_);
    s << indent << "rho_measured_: ";
    Printer<float>::stream(s, indent + "  ", v.rho_measured_);
    s << indent << "phi_measured_: ";
    Printer<float>::stream(s, indent + "  ", v.phi_measured_);
    s << indent << "rhodot_measured_: ";
    Printer<float>::stream(s, indent + "  ", v.rhodot_measured_);
    s << indent << "time_stamp_: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.time_stamp_);
    s << indent << "x_ground_truth_: ";
    Printer<float>::stream(s, indent + "  ", v.x_ground_truth_);
    s << indent << "y_ground_truth_: ";
    Printer<float>::stream(s, indent + "  ", v.y_ground_truth_);
    s << indent << "vx_ground_truth_: ";
    Printer<float>::stream(s, indent + "  ", v.vx_ground_truth_);
    s << indent << "vy_ground_truth_: ";
    Printer<float>::stream(s, indent + "  ", v.vy_ground_truth_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXTENDEDKALMANFILTERS_MESSAGE_RADARMEASUREMENTS_H
